POST https://api-nodejs-7vxu.onrender.com/videos
Content-Type: application/json

{
    "title":"Primeiro Crud, concluido! =D",
    "description":"longa noite, fazendo o crud. foi legal",
    "duration":2000,
    "zone":"pt"
}

###

GET https://api-nodejs-7vxu.onrender.com/videos
#?search={OpA}

###

PUT https://api-nodejs-7vxu.onrender.com/videos/dbaa1cf9-6ff0-4bc4-8614-1bbda56a5526
Content-Type: application/json

{
    "title":"video alterado por requisição put",
    "description":"dados alterados por requisição put",
    "duration":5555,
    "zone":"es"
}

###

DELETE https://api-nodejs-7vxu.onrender.com/videos/b5511f56-a3c1-4f3a-ba8e-7a64948c24ea