POST http://localhost:3333/videos
Content-Type: application/json

{
    "title":"Primeiro Crud, concluido! =D",
    "description":"longa noite, fazendo o crud. foi legal",
    "duration":2000,
    "zone":"pt"
}

###

GET http://localhost:3333/videos
#?search={OpA}

###

PUT https://api-nodejs-7vxu.onrender.com/videos/dbaa1cf9-6ff0-4bc4-8614-1bbda56a5526
PUT http://localhost:3333/videos/5ce5085a-4f2c-4fae-8dde-94a21af3f3fa
Content-Type: application/json

{
    "title":"video alterado por requisição put",
    "description":"dados alterados por requisição put",
    "duration":5555,
    "zone":"es"
}

###

DELETE http://localhost:3333/videos/5ce5085a-4f2c-4fae-8dde-94a21af3f3fa