POST http://localhost:3333/videos
Content-Type: application/json

{
    "title":"Primeiro Crud, concluido! =D",
    "description":"longa noite, fazendo o crud. foi legal",
    "duration":2000,
    "zone":"pt"
}

###

GET http://localhost:3333/videos
#?search={OpA}

###

PUT http://localhost:3333/videos/5ce5085a-4f2c-4fae-8dde-94a21af3f3fa
Content-Type: application/json

{
    "title":"aslkdja",
    "description":"aklsd",
    "duration":12321,
    "zone":"asd"
}

###

DELETE http://localhost:3333/videos/5ce5085a-4f2c-4fae-8dde-94a21af3f3fa